#pragma once

namespace bc
{
	enum ComponentType_e
	{
		COMPONENT_TYPE_CAMERA = 0,
		COMPONENT_TYPE_MANIPULATOR,
		COMPONENT_TYPE_INERTIA_MANIPULATOR,
		COMPONENT_TYPE_ORTHO_MANIPULATOR,
		COMPONENT_TYPE_RENDER_NODE,
		COMPONENT_TYPE_GEO,
		COMPONENT_TYPE_GROUP,
		COMPONENT_TYPE_INSTANCE,
		COMPONENT_TYPE_PARTICLE,
		COMPONENT_TYPE_CUBE_REFLECT,
		COMPONENT_TYPE_LIGHT,
		COMPONENT_TYPE_BOARD,
		COMPONENT_TYPE_SPOT_LIGHT_BOARD,
		COMPONENT_TYPE_VIDEO,
		COMPONENT_TYPE_VIDEO_ROUTE,
		COMPONENT_TYPE_BOARD_ROUTE,
		COMPONENT_TYPE_LIGHTBEAM,
		COMPONENT_TYPE_MEASURE_DISTANCE,
		COMPONENT_TYPE_MEASURE_AREA,
		COMPONENT_TYPE_LOCUS_LINE,
		COMPONENT_TYPE_FLY_LINE,
		COMPONENT_TYPE_VIDEO_FUSION_NODE,
		COMPONENT_TYPE_USER_INTERFACE,
		COMPONENT_TYPE_UI_WIDGET,
		COMPONENT_TYPE_UI_VIDEO,
		COMPONENT_TYPE_UI_BOARD,
		COMPONENT_TYPE_UI_BOARD_INSTANCE,
		COMPONENT_TYPE_DRAW_LINE,
		COMPONENT_TYPE_SHELL,
		COMPONENT_TYPE_SHELL_ROOT,
		COMPONENT_TYPE_PAGED_NODE,
		COMPONENT_TYPE_PAGED_ROOT,
		COMPONENT_TYPE_POLYGON,
		COMPONENT_TYPE_HEAT_MAP_POLYGON,
		COMPONENT_TYPE_POLYGON_SELECTOR,
		COMPONENT_TYPE_ROAD,
		COMPONENT_TYPE_PLOTTING,
		COMPONENT_TYPE_FUSION,
		COMPONENT_TYPE_FUSION_CAMERA,
		COMPONENT_TYPE_BUFFER,
		COMPONENT_TYPE_ACGIS,
		COMPONENT_TYPE_ENERGY,
		COMPONENT_TYPE_BIM,
		COMPONENT_TYPE_BIM_ROOT,
		COMPONENT_TYPE_TIF,
		COMPONENT_TYPE_TIF_ROOT,
		COMPONENT_TYPE_BLANK_MODEL,
		COMPONENT_TYPE_EARTH_NODE,
		COMPONENT_TYPE_NODE_RESOURCE,
		COMPONENT_TYPE_MULTI_FLY_LINE,
		COMPONENT_TYPE_END
	};

	class IComponent
	{
	public:
		virtual int iGetComponentType() = 0;

		void iSetOriginNode(INode* pNode) { m_pNode = pNode; }
		INode* iGetOriginNode() { return m_pNode;  }
	private:
		INode* m_pNode = nullptr;
	};
}

