#pragma once

#include "base/BuildIndoorStateFactory.h"
#include "base/HeatmapFactory.h"
#include "base/VideoInspectionFactory.h"
#include "base/ProjectBasedClient.h"
#include "base/SceneElementLoader.h"

#include "Factory/BCVideoInspectionFactory.h"
#include "Factory/TencentHeatMapFactory.h"
#include "Factory/BuildIndoorFactory.h"
#include "Factory/SubLabelFactory.h"
#include "Factory/SubInstanceLabelFactory.h"

#include "label/CommonLabelFactory.h"
#include "label/InstanceLabelFactory.h"
#include "label/LabelDetailFactory.h"
#include "label/func/IFunc.h"
#include "label/func/ClusterFunc.h"
#include "label/func/DetailScaleFunc.h"
#include "label/func/OverTapFunc.h"
#include "label/func/SmoothMoveFunc.h"
#include "label/func/ReadHeightTifFunc.h"

#include "module/IStateModule.h"
#include "module/BaseModule.h"
#include "module/YBSSModule.h"
#include "module/LayerEditModule.h"
#include "module/DynamicHorizonModule.h"
#include "module/RoamPathModule.h"
#include "module/VideoFusionModule.h"
#include "module/HeatmapModule.h"

#include "utils/pLocal.h"
#include "utils/ThreadWrapper.h"
#include "utils/KMapAdapter.h"
#include "utils/ParamNetImage.h"
#include "utils/ParamParseStream.h"
#include "utils/TweenAnimateForNode.h"
#include "utils/ProjectUtils.h"
#include "utils/tools/BaseStatisticsTool.h"
#include "utils/tools/CircleStatisticsTool.h"
#include "utils/tools/PolygonStatisticsTool.h"
#include "utils/tools/LineStatisticsTool.h"
#include "utils/animate/Easing.h"
#include "utils/animate/EasingAnimate.h"
#include "utils/animate/BaseAnimateObject.h"
#include "utils/animate/TranslateAnimateObject.h"
#include "utils/animate/RotateAnimateObject.h"
#include "utils/animate/ScaleAnimateObject.h"
#include "utils/AnimateWithNodeMg.h"
#include "utils/spdlog/include/spdlog/spdlog.h"
#include "utils/spdlog/include/spdlog/sinks/rotating_file_sink.h"
#include "utils/spdlog/include/spdlog/sinks/daily_file_sink.h"
#include "utils/ProjectLogger.h"
#include "utils/tools/DistanceMeasureTool.h"
#include "utils/tools/AreaMeasureTool.h"
#include "utils/tools/ViewshedAnalysisTool.h"
#include "utils/tools/IsolatedTool.h"
#include "utils/tools/VideoFusionTool.h"

#include "webApi/WebLabelParser.h"
