/*-------------------------------------------------------------------------*/
#ifndef __TW_PREREQUISITES_H__
#define __TW_PREREQUISITES_H__
#pragma once
#include <math.h>
#include <stdio.h>
// Needed for OGRE_WCHAR_T_STRINGS below
#include <string>
//#include <hash_map>
// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4503)

// disable: "conversion from 'double' to 'float', possible loss of data
#   pragma warning (disable : 4244)

// disable: "truncation from 'double' to 'float'
#   pragma warning (disable : 4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning (disable : 4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning (disable : 4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception
// specifications in the ANSI C++ draft.
#   pragma warning( disable : 4290 )

// disable: "no suitable definition provided for explicit template
// instantiation request" Occurs in VC7 for no justifiable reason on all
// #includes of Singleton
#   pragma warning( disable: 4661)

// disable: deprecation warnings when using CRT calls in VC8
// These show up on all C runtime lib code in VC8, disable since they clutter
// the warnings with things we may not be able to do anything about (e.g.
// generated code from nvparse etc). I doubt very much that these calls
// will ever be actually removed from VC anyway, it would break too much code.
#	pragma warning( disable: 4996)

// disable: "conditional expression constant", always occurs on 
// OGRE_MUTEX_CONDITIONAL when no threading enabled
#   pragma warning (disable : 201)






    // Define ogre version
    #define OGRE_VERSION_MAJOR 1
    #define OGRE_VERSION_MINOR 6
    #define OGRE_VERSION_PATCH 3
	#define OGRE_VERSION_SUFFIX ""
    #define OGRE_VERSION_NAME "Shoggoth"


  //  #           define HashMap ::std::hash_map
	//#           define HashSet ::std::hash_set


    /** In order to avoid finger-aches :)
    */



	typedef std::string _StringBase;

	typedef _StringBase String;


		#define OGRE_AUTO_MUTEX
		#define OGRE_LOCK_AUTO_MUTEX
		#define OGRE_MUTEX(name)
		#define OGRE_STATIC_MUTEX(name)
		#define OGRE_STATIC_MUTEX_INSTANCE(name)
		#define OGRE_LOCK_MUTEX(name)
		#define OGRE_LOCK_MUTEX_NAMED(mutexName, lockName)
		#define OGRE_AUTO_SHARED_MUTEX
		#define OGRE_LOCK_AUTO_SHARED_MUTEX
		#define OGRE_NEW_AUTO_SHARED_MUTEX
		#define OGRE_DELETE_AUTO_SHARED_MUTEX
		#define OGRE_COPY_AUTO_SHARED_MUTEX(from)
        #define OGRE_SET_AUTO_SHARED_MUTEX_NULL
        #define OGRE_MUTEX_CONDITIONAL(name) if(true)
		#define OGRE_THREAD_SYNCHRONISER(sync) 
		#define OGRE_THREAD_WAIT(sync, lock) 
		#define OGRE_THREAD_NOTIFY_ONE(sync) 
		#define OGRE_THREAD_NOTIFY_ALL(sync) 
		#define OGRE_THREAD_POINTER(T, var) T* var
		#define OGRE_THREAD_POINTER_SET(var, expr) var = expr
		#define OGRE_THREAD_POINTER_DELETE(var) OGRE_DELETE var; var = 0
		#define OGRE_THREAD_POINTER_GET(var) var



// Pre-declare classes
// Allows use of pointers in header files without including individual .h
// so decreases dependencies between files


namespace bc
{
	class Angle;
	class Radian;
	class Ray;
	class Math;

	class Matrix3;
	class Matrix4;
	class Quaternion;

	//class Vector2;
	//class Vector3;
	//class Vector4;

	class Axis;

	class Plane;
	class Ray;
	class BoundingBox;
	class BoundingSphere;
	class Sphere;
	struct RayIntersect;
	struct IntersectPoint;
}


  
/* Include all the standard header *after* all the configuration
settings have been made.
*/
#include "StdHeaders.h"
//#include "../math.h"


#endif // __OgrePrerequisites_H__



